
export default  {
  FETCH_PATIENT_REQUEST: `FETCH_PATIENT_REQUEST`,
  FETCH_PATIENT_SUCCESS: `FETCH_PATIENT_SUCCESS`,
  FETCH_PATIENT_FAIL: `FETCH_PATIENT_FAIL`,

  ADD_PATIENT_REQUEST: `ADD_PATIENT_REQUEST`,
  ADD_PATIENT_SUCCESS: `ADD_PATIENT_SUCCESS`,
  ADD_PATIENT_FAIL: `ADD_PATIENT_FAIL`


};
