
export default  {
  FETCH_HOSPITAL_REQUEST: `FETCH_HOSPITAL_REQUEST`,
  FETCH_HOSPITAL_SUCCESS: `FETCH_HOSPITAL_SUCCESS`,
  FETCH_HOSPITAL_FAIL: `FETCH_HOSPITAL_FAIL`,

  ADD_HOSPITAL_REQUEST: `ADD_HOSPITAL_REQUEST`,
  ADD_HOSPITAL_SUCCESS: `ADD_HOSPITAL_SUCCESS`,
  ADD_HOSPITAL_FAIL: `ADD_HOSPITAL_FAIL`


};
