
export default  {
  CHECK_KEY_LOCATIONS_REQUEST: 'CHECK_KEY_LOCATIONS_REQUEST',
  CHECK_KEY_LOCATIONS_SUCCESS: 'CHECK_KEY_LOCATIONS_SUCCESS',
  CHECK_KEY_LOCATIONS_FAIL: 'CHECK_KEY_LOCATIONS_FAIL',



  UPLOAD_KEY_LOCATIONS_REQUEST: 'UPLOAD_KEY_LOCATIONS_REQUEST',
  UPLOAD_KEY_LOCATIONS_SUCCESS: 'UPLOAD_KEY_LOCATIONS_SUCCESS',
  UPLOAD_KEY_LOCATIONS_FAIL: 'UPLOAD_KEY_LOCATIONS_FAIL',






};
