
export default  {
  USER_GET_REQUEST: `USER_GET_REQUEST`,
  USER_GET_SUCCESS: `USER_GET_SUCCESS`,
  USER_GET_FAIL: `USER_GET_FAIL`,


  USER_UPDATE_REQUEST: `USER_UPDATE_REQUEST`,
  USER_UPDATE_SUCCESS: `USER_UPDATE_SUCCESS`,
  USER_UPDATE_FAIL: `USER_UPDATE_FAIL`


};
